#!/usr/bin/env bash

# Copyright (C) 2018-19 Akhil Narang
# SPDX-License-Identifier: GPL-3.0-only

# Script with some aliases and exports

if [[ "$(command -v hub)" ]]; then
    alias git='hub'
fi

# Miscellaneous aliases
alias setperf='echo "performance" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias setsave='echo "powersave" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias path='echo ${PATH}'

# Set default editor to nano
export EDITOR="nano"

# Set timezone
export TZ="Asia/Kolkata"
